[tool.poetry]
name = "carshare"
version = "0.1.0"
description = "A web based Car Share management platform."
authors = ["George Goldberg <george@appletreetechnology.com>"]
license = "AGPL Version 3"

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.0"
django-tailwind = "^3.0.1"
psycopg-binary = "^3.0.7"
black = "^21.12b0"
django-allauth = "^0.47.0"
django-crispy-forms = "^1.13.0"
Pillow = "^8.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
